name: edelweissfe
channels:
  - https://repo.prefix.dev/matthiasneuner/edelweiss
  - conda-forge
dependencies:
  - python=3.14
  - python-freethreading=3.14
  - pip
  - setuptools
  - cython
  - numpy
  - scipy
  - sympy
  - matplotlib
  - prettytable
  - gstools
  - vtk
  - pyvista
  - mkl
  - mkl-include
  - suitesparse
  - compilers
  - cmake
  - make
  - eigen
  - libboost-devel
  - amgcl
  - autodiff=1.1.2
  - fastor
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme>=3.1.0
  - numpydoc
  - docutils
