#!/usr/bin/env python3
"""Regenerate zsymm_complete.txt: every mesh node lying on the z = 0 symmetry plane.

WHY THIS EXISTS
    The z_symm_concrete / z_symm_steel sets imported from the Abaqus source model are incomplete --
    516 nodes lie exactly on the symmetry plane without being members. Prescribing u3 = 0 only on the
    imported sets therefore leaves those nodes free to move out of the symmetry plane, silently. This
    script derives the set from the mesh geometry instead, so it is complete by construction.

    It replaces the former zsymm_free_block.txt, which additionally subtracted the tie constraints'
    slave nodes by hand. That subtraction is no longer needed: the solver option
    `mpcDirichletConflicts=reconcile` settles the Dirichlet/tie overlap itself, dropping the
    redundant constraint equation and reporting anything it drops that was not already implied.

    Subtracting nodes was actively harmful, not merely fragile: adaptive refinement propagates a node
    set to newly created nodes only when the parent face lies *fully* within the set, so every face
    touching an excluded node stopped propagating the boundary condition to its children.

RE-RUN THIS whenever the mesh changes:
    python3 make_zsymm_complete.py
"""

TOLERANCE = 1e-6
MESHES = (("mesh/concrete_edelweissfe.inp", 0), ("mesh/steel_edelweissfe.inp", 0))
OUTPUT = "zsymm_complete.txt"


def nodesOf(path, offset=0):
    """The {label: coordinates} of every *NODE in an Abaqus-style input file."""

    nodes, inNodeBlock = {}, False
    for line in open(path):
        stripped = line.strip()
        if not stripped or stripped.startswith("**"):
            continue
        if stripped.startswith("*"):
            inNodeBlock = stripped.upper().startswith("*NODE")
            continue
        if inNodeBlock:
            fields = [f for f in stripped.split(",") if f.strip()]
            nodes[int(fields[0]) + offset] = [float(f) for f in fields[1:4]]
    return nodes


allNodes = {}
for path, offset in MESHES:
    allNodes.update(nodesOf(path, offset))

onPlane = sorted(label for label, xyz in allNodes.items() if abs(xyz[2]) < TOLERANCE)
print("{:} node(s) in the mesh, {:} on the z = 0 symmetry plane".format(len(allNodes), len(onPlane)))

with open(OUTPUT, "w") as f:
    f.write("** GENERATED by make_zsymm_complete.py -- do not edit by hand.\n")
    f.write("** Every node on the z = 0 symmetry plane (|z| < {:g}), {:} in total.\n".format(TOLERANCE, len(onPlane)))
    f.write("** The imported z_symm_concrete/z_symm_steel sets are incomplete by 516 nodes; see the\n")
    f.write("** script's docstring for why that matters and why no nodes are subtracted here.\n")
    f.write("*NSET, NSET=z_symm_all\n")
    for start in range(0, len(onPlane), 10):
        f.write(", ".join(str(label) for label in onPlane[start : start + 10]) + ",\n")
print("wrote", OUTPUT)
